[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

via_ir = true
optimizer = true
optimizer_runs = 200

private_key = "${PRIVATE_KEY}"

remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[rpc_endpoints]
mainnet = "${RPC_URL}"
sepolia = "${RPC_URL_TEST}"
amoy = "${RPC_URL_AMOY}"
base = "${RPC_URL_BASE_SEPOLIA}"
